### ISSUE TITLE
Scroll bar to return to main menu is inconsistent across modes

### ISSUE THREAD

**Issue by thaeli** [AEFeinstein/Swadge-Devkit-Fw#103]
The bar that needs to fill up before returning to the main menu moves much slower on the Joust title screen and in the Gallery.

**Comment by AEFeinstein** [comment]
This is already fixed in https://github.com/AEFeinstein/Swadge-Devkit-Fw/tree/fast_draw

It turns out that the ESP is not happy if you spend too much time in a a function registered with `os_timer_setfn()`, but it's perfectly happy with spending a lot of time the function registered with `system_os_task()`. @cnlohr pointed me in the right direction with this one.

I moved the call to `updateOLED()` to the happy place and it now draws pretty much as soon as the firmware changes a pixel, and is perfectly stable to boot. This fixes both the scroll bar draw speed, which used to be tied to a mode's chosen framerate, and also allows music to be played during intensive OLED updates.

**Comment by AEFeinstein** [comment]
Merged in https://github.com/AEFeinstein/Swadge-Devkit-Fw/pull/105
