### ISSUE TITLE
make all does not recompile when a header file changed

### ISSUE THREAD

**Issue by bbkiwi** [AEFeinstein/Swadge-Devkit-Fw#21]
**Expected Behavior**
Would like when code changes make burn creates image with that change

**Actual Behavior**
If only ccconfig.h is changed. ie NUM_LIN_LEDS from 6 to 16
make burn or make all does not see this, so make burn just burns previous image
So in this case must first run make clean.
Is there anyway for the makefile to tell if ccconfig.h gets changed?
Tested other .h files and the same things happens.

Related:
[https://stackoverflow.com/questions/44020890/gnu-make-does-not-recompile-when-a-header-file-changed](url)

**Comment by AEFeinstein** [comment]
Not recompiling is expected behavior for the way the makefile is written. The same thing happens if you modify anything in the makefile's ``DEFINES_LIST``. It's somewhat rare that the only change occurs in a header file, but you've found one case.

If you want to modify the makefile to recompile header-only changes, go for it. This project is small enough that recompiling the whole thing isn't troublesome.

Also related: https://nathandumont.com/blog/automatically-detect-changes-in-header-files-in-a

**Comment by AEFeinstein** [comment]
This should be resolved with efad4b88a1a4d737751541d0b54f3ce6c8f2c2e9
