### ISSUE TITLE
Color Shake Tweaks

### ISSUE THREAD

**Issue by jt-moriarty** [AEFeinstein/Swadge-Devkit-Fw#93]
Summary of 12-11 meeting notes / mode review:

Determine time table for final changes (estimated 12-16).

Notes from @adangert / @jt-moriarty review of sub-modes:

Beat Spin / Beat Select:
-Recommend disable or at least move to later in the cycle of sub-modes.

@adangert claimed (time-permitting):
Shock Change / Shock Chaotic:
-Sub-modes are interactive / responsive, should be better with minor tweaks.

Roll Ball / Roll 3 Balls:
-Sub-modes might be in a more responsive state if the physics of the balls operated closer to raw accelerometer input.

@jt-moriarty claimed (time-permitting):
Tilt A Color:
-Either by adding meters showing accelerometer values, labeling axes on the triangle, or modifying which axes control the colors / triangle dimensions, this sub-mode should be able to be made more intuitive.

Twirl A Color:
-May rework the behavior of this sub-mode to be something more readily apparent (compass-like behavior?) or remove this sub-mode if time does not permit.

Shake To Fill:
-Modifying LED fill behavior and shake responsiveness may make this sub-mode feel more responsive.

**Comment by AEFeinstein** [comment]
Other thing to think about are names for the modes. Clearer names may set better expectations or push people towards more correct behaviors. My takes on the notes.

@adangert 

* **Beat Spin / Beat Select** - I'd rather move it to the end of the mode list than disable it.
* **Shock Change / Shock Chaotic** - Not sure what "minor tweaks" are. I know Dac had mentioned using rotating or random colors for Shock Change rather than just red, which is very reasonable.
* **Roll Ball / Roll 3 Balls** - Good luck digging through physics code. Be careful not to have unintended consequences for other modes when modifying any sort of filtering.

@jt-moriarty 

* **Tilt A Color** - What would the labels be, XYZ? RGB? Something else? Try not to make it look too cluttered, I kind of like the elegant triangle. I'm not sure if that's possible though.
* **Twirl A Color** - This may just need a label like Tilt A Color. The one thing an accelerometer can't detect is compass like behavior (i.e. put it flat on a table, spin it around). You need a gyro or magnetomoeter for that.
* **Shake To Fill** - Agreed this should be more responsive.

12/16 sounds like a fine time for final changes. When you have something testable, let me know and I'll build & share with Dac.

**Comment by thaeli** [comment]
Made some tweaks in #94

**Comment by adangert** [comment]
made some changes in #99

**Comment by AEFeinstein** [comment]
@adangert , @thaeli , @jt-moriarty anything else that you want to tweak tomorrow? Otherwise I'm gonna close this one.

**Comment by thaeli** [comment]
I'm happy with the way it works in latest master.
